language: php

php:
  - 7.4
  - 7.3
  - 7.2

env:
  - SYMFONY_VERSION=5.0.*
  - SYMFONY_VERSION=4.4.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require --prefer-source --no-interaction symfony/symfony:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php vendor/bin/php-coveralls -v --exclude-no-stmt; fi
